package br.ufrpe.geekMart.negocio.classesBasicas;

public enum SubcategoriasEnum {
    POKEMÓN, MÁRIO_BROS, NARUTO, CAVALEIROS_DO_ZODÍACO, DRAGON_BALL, MARVEL, DC, DISNEY, YUGI_OH, MAGIC, HOT_TOY,
    SH_FIGUARTS, CLOTH_MYTH, PLAY_ARTS, POP_FUNKO, IRON_STUDIOS, STAR_WARS, HARRY_POTTER, SENHOR_DOS_ANÉIS,
    CHAVEIROS, COLARES, PULSEIRAS, BRINCOS, FILMES, SÉRIES, ANIMES, HQS, MANGÁS;
}
